spring.application.name=project

# 파일 업로드 경로
file.upload.path=C:/upload/

# 데이터베이스 - MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/aloha?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&autoReconnection=true
spring.datasource.username=aloha
spring.datasource.password=123456

# MyBatis 설정
# mybatis.config-location=classpath:mybatis-config.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.aloha.project.dto
mybatis.mapper-locations=classpath:com/aloha/project/mapper/**/*.xml


# 파일 업로드 설정
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB

# profile 분기에 따라 불러올 파일
# application-[profile].properties
# application-oauth-kakao.properties
spring.profiles.include=oauth-kakao

# 카카오페이 설정
kakaopay.secret-key=DEVC085543349485E7325060E7D812435918D5A2
kakaopay.cid=TC0ONETIME
kakaopay.ready-url=https://open-api.kakaopay.com/online/v1/payment/ready
kakaopay.approve-url=https://open-api.kakaopay.com/online/v1/payment/approve
kakaopay.cancel-url=https://open-api.kakaopay.com/online/v1/payment/cancel
openai.api.key=
com.aloha.project.secret-key=YnSugF%2YB!qXWfDfr*rN=HUWu%A8B-abzFMXBTtn9Q*8-7gj^TJc!_rnHZMMNCw

#GOOGLE
spring.security.oauth2.client.registration.google.client-id={google_id}
spring.security.oauth2.client.registration.google.client-secret={google_key}
spring.security.oauth2.client.registration.google.scope=profile,email

# NAVER OAuth Settings

spring.security.oauth2.client.registration.naver.client-id={naver_id}
spring.security.oauth2.client.registration.naver.client-secret={naver_key}
spring.security.oauth2.client.registration.naver.client-name=Naver
spring.security.oauth2.client.registration.naver.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.naver.redirect-uri=http://localhost:8080/login/oauth2/code/naver
spring.security.oauth2.client.registration.naver.scope=name,email

spring.security.oauth2.client.provider.naver.authorization-uri=https://nid.naver.com/oauth2.0/authorize
spring.security.oauth2.client.provider.naver.token-uri=https://nid.naver.com/oauth2.0/token
spring.security.oauth2.client.provider.naver.user-info-uri=https://openapi.naver.com/v1/nid/me
spring.security.oauth2.client.provider.naver.user-name-attribute=response